#testing
name: Build and Deploy ASP.Net Core App to Azure Web App

on:
  push:
    branches:
      - master  # Trigger the workflow when pushing to the master branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]  # Specify your self-hosted runner by label

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use the official checkout action

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4  # Use the official setup-dotnet action
        with:
          dotnet-version: '8.x'

      - name: Build the application
        run: dotnet build --configuration Release  # Build the app in Release mode

      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish  # Publish the app

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4  # Upload the published app as an artifact
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: [self-hosted, Windows, X64]  # Use your self-hosted runner for deployment
    needs: build  # Ensure deployment only happens after the build job is completed

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4  # Download the published app
        with:
          name: .net-app

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash  # Install Azure CLI on self-hosted runner

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Use the Azure credentials from GitHub Secrets

      - name: Deploy to Azure Web App
        run: |
          az webapp deploy --resource-group <your-resource-group> --name <your-app-name> --src-path ./publish  # Deploy using Azure CLI
