name: Build .NET 8 Application

on:
  push:
    branches:
      - master  # or the branch you're working with
  pull_request:
    branches:
      - master  # or the branch you're working with

jobs:
  build:
    # Target the self-hosted runner with the specific labels
    runs-on: [self-hosted, Windows, X64, SPC122]  # Add all the labels here

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Official GitHub Action for checking out code

    - name: Set up .NET 8 SDK
      uses: actions/setup-dotnet@v3  # Official GitHub Action for setting up .NET SDK
      with:
        dotnet-version: '8.x'  # Specify the .NET version you want to use

    - name: Install dependencies
      run: dotnet restore  # Restore project dependencies

    - name: Build the application
      run: dotnet build --configuration Release  # Build the application

    - name: Run tests
      run: dotnet test --configuration Release  # Run tests

    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish  # Publish the application
