name: Build and Deploy ASP.Net Core App to Azure Web App

on:
  push:
    branches:
      - master  # Trigger the workflow when pushing to the master branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  # Specify the .NET version to use

      - name: Build the application
        run: dotnet build --configuration Release  # Build the app in Release mode

      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish  # Publish the app

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4  # Upload the published app as an artifact
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: self-hosted  # Use the self-hosted runner for deployment
    needs: build  # Ensure deployment only happens after the build job is completed

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app  # Download the published app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3  # Use the Azure Web Apps Deploy action
        with:
          app-name: 'your-azure-app-name'  # Replace with your Azure Web App name
          slot-name: 'Production'  # Use the production slot (or specify a different slot if necessary)
          package: ./publish  # Path to the published app (this was where we saved it earlier)
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_TEST1234 }}  # Use the publish profile from GitHub Secrets
